### ISSUE TITLE
swissmedic fails

### ISSUE THREAD

**Issue by ephaee** [epha/download#15]
```
EMIL: I'm ready, if you are? Type help for help.
> swissmedic
EMIL: Added 'swissmedic' to the queue (4 jobs)!
EMIL: You can run queue with 'go'
> go
EMIL@SWISS: Querying at 2015-02-16T15:57:09.557Z
EMIL@SWISS: Search link in https://www.swissmedic.ch/
EMIL@SWISS: Download file and save to 'data/auto/swissmedic.xlsx'
WORKING: DOWNLOADING FILE.._http_client.js:73
    throw new TypeError('Request path contains unescaped characters.');
          ^
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Object.module.exports.file (~/Git/download/lib/download.js:130:28)
    at module.exports.download (~/Git/download/jobs/swissmedic.js:39:14)
    at (~/Git/download/node_modules/async/lib/async.js:551:21
    at (~/Git/download/node_modules/async/lib/async.js:227:13
    at iterate ((~/Git/download/node_modules/async/lib/async.js:134:13)
    at (~/Git/download/node_modules/async/lib/async.js:145:25
    at (~/Git/download/node_modules/async/lib/async.js:229:17
```

**Comment by ephaee** [comment]
Was fixed in https://github.com/epha/download/commit/df1a225a4ad36575c9f10b42d67671b1523f8cf2 @Jonas74  thanks!
